# Generated by Django 3.1.3 on 2021-06-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_verifiedemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifiedemail',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
