# Generated by Django 4.0.5 on 2023-10-01 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210629_0759'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerifiedEmail',
        ),
    ]
