# Generated by Django 3.1.3 on 2021-04-22 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('bio', models.TextField(max_length=500)),
                ('location', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('total_vote', models.IntegerField(default=0, editable=False)),
                ('image', models.ImageField(upload_to='candidate_images/', verbose_name='Candidate Pic')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.position')),
            ],
        ),
    ]
