# Generated by Django 3.1.3 on 2021-05-02 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_auto_20210429_0814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='location',
            new_name='address',
        ),
    ]
