# Generated by Django 3.1.3 on 2021-07-03 06:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0008_setdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setdate',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
