# Generated by Django 3.1.3 on 2021-09-25 02:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0010_auto_20210925_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetRegistrationDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('registration_duration', models.DurationField()),
                ('registration_end_date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='setvotedate',
            name='registration_duration',
        ),
        migrations.RemoveField(
            model_name='setvotedate',
            name='registration_end_date',
        ),
        migrations.RemoveField(
            model_name='setvotedate',
            name='registration_start_date',
        ),
    ]
