# Generated by Django 3.1.3 on 2021-09-25 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0011_auto_20210925_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setregistrationdate',
            name='registration_duration',
        ),
        migrations.RemoveField(
            model_name='setvotedate',
            name='voting_duration',
        ),
    ]
