# Generated by Django 3.1.3 on 2021-09-25 05:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0012_auto_20210925_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setregistrationdate',
            name='registration_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='setvotedate',
            name='voting_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
