# Generated by Django 3.1.3 on 2021-09-25 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0013_auto_20210925_1111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SetRegistrationDate',
        ),
        migrations.RenameField(
            model_name='setvotedate',
            old_name='voting_end_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='setvotedate',
            old_name='voting_start_date',
            new_name='start_date',
        ),
    ]
