# Generated by Django 3.1.3 on 2021-09-28 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0015_publishresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublishResult',
        ),
        migrations.DeleteModel(
            name='SetVoteDate',
        ),
    ]
