# Generated by Django 3.1.3 on 2021-09-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0016_auto_20210928_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproveResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_result', models.BooleanField(default=False)),
            ],
        ),
    ]
