# Generated by Django 3.1.3 on 2021-09-28 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0017_approveresult'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApproveResult',
            new_name='Result',
        ),
    ]
